config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :teachers, except: [:index] do
    scope module: :teachers do
      resources :debts, except: [:edit] do
        scope module: :debts do
          resources :payments
        end
      end
      resources :students
      resources :montly_payments, only: [:create]
      resources :learning_resources
      resources :reviews, except: [:index]
    end
    resources :groups # TODO: this line seems like is not required
    resources :documents
    resources :groups do
      resources :attendances, except: [:edit, :update, :destroy]
    end
    resources :student_learning_resources, only: [:new, :create, :destroy]
  end

  resources :students, except: [:index, :create, :destroy] do
    scope module: :students do
      resources :learning_resources, only: [:index]
      resources :attendances, only: [:index]
      resources :reviews, only: [:index]
      resources :student_learning_resources, only: [:index]
    end
  end
end
# rubocop:enable Metrics/BlockLength

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  store :days_of_the_week, accessors: [:sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday]
  validates :from_time, :to_time, presence: true

  has_many :group_members, dependent: :destroy
  has_many :users, through: :group_members
  has_many :attendances, dependent: :delete_all
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_user, :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.all
    redirect_to teacher_groups_url(@user)
  end

  def show
    render "teachers/groups/show"
  end

  def new
    @group = Group.new
    render "teachers/groups/new"
  end

  def edit
    render "teachers/groups/edit"
  end

  def create
    @group = @user.groups.new(group_params)

    return redirect_to teacher_url(@user), notice: "Group was successfully created." if @group.save

    render :new, status: :unprocessable_entity
  end

  def update
    if @group.update(group_params)
      return redirect_to teacher_group_url(@user, @group), notice: "Group was successfully updated."
    end

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @group.destroy

    redirect_to teacher_url(@user), notice: "Group was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:teacher_id])
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :from_time, :to_time, days_of_the_week: {})
  end
end

app/controllers/teachers/debts/payments_controller.rb
module Teachers
  module Debts
    class PaymentsController < ApplicationController
      before_action :authenticate_user!, :set_user
      before_action :set_debt, oonly: [:new]

      def new
        @payment = Payment.new
      end

      def create
        payment = PaymentsService.new(payment_params)

        return redirect_to teacher_debts_url(@user), notice: "Payment was successfully applied." if payment.apply

        render :new, status: :unprocessable_entity
      end

      private

      def payment_params
        params.require(:payment).permit(:amount, :debt_id)
      end

      def set_user
        user_id = current_user.id || params[:id]
        @user = User.find(user_id)
      end

      def set_debt
        @debt = Debt.find(params[:debt_id])
      end
    end
  end
end

app/controllers/teachers/debts_controller.rb
module Teachers
  class DebtsController < ApplicationController
    before_action :authenticate_user!, :set_user
    before_action :set_debt, only: [:edit, :update, :destroy, :show]
    before_action :set_teacher_students

    def index
      @debts = @user.my_debts.where(status: DEBTS_STATUS[:pending]).paginate(page: params[:page], per_page: PER_PAGE)
    end

    def show; end

    def new
      @debt = @user.my_debts.new
    end

    def edit; end

    def create
      @debt = @user.my_debts.new(debt_params)

      return redirect_to teacher_debts_url(@user), notice: "Debt was created." if @debt.save

      render :new, status: :unprocessable_entity
    end

    def update
      return redirect_to teacher_debts_url(@user), notice: "Debt was updated." if @debt.update(debt_params)

      render :edit, status: :unprocessable_entity
    end

    def destroy
      @debt.destroy

      redirect_to teacher_debts_url(@user), notice: "Debt was successfully destroyed."
    end

    private

    def set_debt
      @debt = Debt.find(params[:id])
    end

    def debt_params
      params.require(:debt).permit(:amount, :concept, :teacher, :description, :student_id, :status)
    end

    def set_user
      user_id = current_user.id || params[:id]
      @user = User.find(user_id)
    end

    def my_students_ids
      # TODO: nicer approach would be having a instance method responsible of getting that records. (@teacher.students)
      @user.group_members.pluck(:user_id)
    end

    def set_teacher_students
      @my_students = User.where(id: my_students_ids).select(:name, :id)
    end
  end
end

app/controllers/teachers/learning_resources_controller.rb
module Teachers
  class LearningResourcesController < ApplicationController
    before_action :authenticate_user!, :set_user
    before_action :set_teachers_learning_resource, only: [:show, :edit, :update, :destroy]

    def index
      @teacher_learning_resources = @user.learning_resources.paginate(page: params[:page], per_page: PER_PAGE)
    end

    def show; end

    def new
      @teachers_learning_resource = @user.learning_resources.new
    end

    def edit; end

    def create
      @teachers_learning_resource = @user.learning_resources.new(learning_resource_params)

      if @teachers_learning_resource.save
        redirect_to teacher_learning_resources_url(@user), notice: "Learning resource was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @teachers_learning_resource.update(learning_resource_params)
        redirect_to teacher_learning_resources_url(@teachers_learning_resource),
                    notice: "Learning resource was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @teachers_learning_resource.destroy

      redirect_to teacher_learning_resources_url(@user), notice: "Learning resource was successfully destroyed."
    end

    private

    def set_user
      user_id = current_user.id || params[:id]
      @user = User.find(user_id)
    end

    def set_teachers_learning_resource
      @teachers_learning_resource = LearningResource.find(params[:id])
    end

    def learning_resource_params
      params.require(:learning_resource).permit(:name, :description, :belt, :resource)
    end
  end
end

app/controllers/teachers/montly_payments_controller.rb
module Teachers
  class MontlyPaymentsController < ApplicationController
    before_action :authenticate_user!, :set_user

    def create
      my_students.map do |member|
        member.user.debts.create!(
          amount: member.user.student_information.montly_payment,
          concept: "Mensualidad #{Date.today.strftime("%B")}",
          teacher: @user,
          status: "pending"
        )
      end

      redirect_to teacher_debts_url(@user), notice: "Montly payment successfully aplied."
    end

    private

    def set_user
      @user = User.find(params[:teacher_id])
    end

    def my_students
      @user.group_members
    end
  end
end

app/controllers/teachers/reviews_controller.rb
module Teachers
  class ReviewsController < ApplicationController
    before_action :authenticate_user!, :set_user
    before_action :set_teachers_review, only: [:show, :edit, :update, :destroy]
    before_action :set_teacher_students, only: [:new, :edit]

    def show; end

    def new
      @review = Review.new
    end

    def edit; end

    def create
      @review = Review.new(teachers_review_params.merge(teacher: @user))

      return redirect_to teacher_review_url(@user, @review), notice: "Review was successfully created." if @review.save

      render :new, status: :unprocessable_entity
    end

    def update
      if @review.update(teachers_review_params)
        redirect_to teacher_review_url(@user, @review), notice: "Review was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @review.destroy
      redirect_to teacher_student_path(@user, @review.student_id), notice: "Review was successfully destroyed."
    end

    private

    def set_teachers_review
      @review = Review.find(params[:id])
    end

    def set_user
      @user = User.find(params[:teacher_id])
    end

    def teachers_review_params
      params.require(:review).permit(:review, :learning_resource_id, :student_id)
    end

    def my_students_ids
      # TODO: nicer approach would be having a instance method responsible of getting that records. (@teacher.students)
      @user.group_members.pluck(:user_id)
    end

    def set_teacher_students
      @my_students = User.where(id: my_students_ids).select(:name, :id)
    end
  end
end

app/controllers/teachers/students_controller.rb
module Teachers
  class StudentsController < ApplicationController
    before_action :authenticate_user!, :set_user
    before_action :set_student, only: [:show, :edit, :update, :destroy]

    def index
      @students = User.where(id: my_students_ids).paginate(page: params[:page], per_page: PER_PAGE)
    end

    def show
      @attendances = @student.attendances.where(date: from_date..to_date)
      @attendance_stats = @attendances.group(:present).count
    end

    def new
      @student = User.new
    end

    def edit; end

    def create
      @student = User.new(user_params.merge(password: new_user_temp_password, role: "student"))
      if @student.save
        return redirect_to teacher_students_path(@user),
                           notice: "Student created with password #{new_user_temp_password}."
      end

      render :new, status: :unprocessable_entity
    end

    def update
      if @student.update(user_params)
        return redirect_to teacher_students_url(@user), notice: "Student successfully updated."
      end

      render :edit, status: :unprocessable_entity
    end

    def destroy
      @student.destroy
      redirect_to teacher_students_url(@user), notice: "Student successfully destroyed."
    end

    private

    def set_student
      @student = User.find(params[:id])
    end

    def set_user
      @user = User.find(params[:teacher_id])
    end

    def user_params
      params.require(:user).permit(
        :email, :password, :name, :role, :birth_date, :belt,
        group_member_attributes: [:group_id],
        student_information_attributes: [
          :ocupation, :civil_status, :tutor_name, :cellphone, :health_insurance, :montly_payment
        ]
      )
    end

    def new_user_temp_password
      Date.parse(user_params[:birth_date]).strftime('%d%m%y')
    end

    def my_students_ids
      @user.group_members.map(&:user_id)
    end

    def from_date
      params[:from_date] || 1.month.ago
    end

    def to_date
      params[:to_date] || Date.today
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!, :set_user

  def show
    # TODO: This could be a pagination method
    @groups = @user.groups.all
    @total_of_students = @user.group_members.count # TODO: Apply conty catch in to database
    @total_of_learning_resources = @user.learning_resources.count
    # TODO: Add days of the weey to this query
    @in_progress_group = @user.groups
                              .where("from_time <= ?", Time.new)
                              .where("to_time >= ?", Time.new).last
  end

  def new
    @teacher = User.new
  end

  def edit; end

  def create
    @teacher = User.new(user_params.merge(password: new_temp_password, role: "teacher"))

    if @teacher.save
      return redirect_to teacher_path(@user), notice: "Teacher created with password #{new_temp_password}."
    end

    render :new, status: :unprocessable_entity
  end

  def update
    return redirect_to teacher_url(@user), notice: "Profile was successfully updated." if @user.update(user_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @user.destroy
    redirect_to teachers_url, notice: "Teacher was successfully destroyed."
  end

  private

  def set_user
    user_id = params[:id] || current_user.id
    @user = User.find(user_id)
  end

  def user_params
    params.require(:user).permit(:email, :password, :name, :birth_date, :belt)
  end

  def new_temp_password
    Date.parse(user_params[:birth_date]).strftime('%d%m%y')
  end
end

app/views/teachers/groups/_days_of_the_week.html.erb
<div id="days of the week" class="">
  <% days_of_the_week.map do |day, value| %>
    <% if value == "1" %>
      <span class="tag is-info is-medium">
        <%= day %>
        <i class="fas fa-check ml-2"></i> 
      </span>
    <% else %>
      <span class="tag is-ligth is-medium"><%= day %></span>
    <% end %>
  <% end %>
</div>

app/views/teachers/groups/_form.html.erb
<%= form_with(model: group, url: url, method: method) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= form.label :name, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control">
          <%= form.text_field :name, value: group.name, required: true, class: "input" %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= form.label :from_time, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control">
          <%= form.time_field :from_time, value: group.from_time&.strftime('%T'), required: true, class: "input" %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= form.label :to_time, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control">
          <%= form.time_field :to_time, value: group.to_time&.strftime('%T'), required: true, class: "input" %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= form.label :days_of_the_week, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field pt-2">
        <%= form.fields_for :days_of_the_week do |field| %>
        
          <% [:sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday].each do |day| %>
            <label class="checkbox mr-3">
              <%= day.to_s.capitalize %>
              <%= field.check_box day, { checked: !group[:days_of_the_week][day].to_i.zero? } %>
            </label>
          <% end %>

        <% end %>
      </div>
    </div>
  </div>

  <div class="is-flex is-justify-content-flex-end mb-4 mr-3">
    <%= form.submit class: "button is-success is-outlined" %>
  </div>
  
<% end %>

app/views/teachers/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p>
    <strong>Name:</strong>
    <%= group.name %>
  </p>

  <p>
    <strong>From </strong>
    <%= group.from_time.strftime('%k:%M:%S') %>
    <strong>To </strong>
    <%= group.to_time.strftime('%k:%M:%S') %>
  </p>

  <p>
    <strong>Enrolled students</strong>
    <%= group.group_members.count  %>
  </p>

  <p>
    <strong>Training days</strong>
    <%= render "teachers/groups/days_of_the_week", days_of_the_week: group.days_of_the_week %>
  </p>


</div>

app/views/teachers/groups/edit.html.erb
<div class="container pt-5">
  <h1 class="title">Edit group</h1>

  <%= render "teachers/groups/form", group: @group, method: :patch, url: teacher_group_url(@user, @group) %>

  <div class="is-flex is-justify-content-flex-end">
    <%= link_to(teacher_group_path(@user, @group), class: "button is-info is-outlined mr-3") do %>
      <i class="fas fa-undo"></i>
      <span class="ml-2">Back to group</span>
    <% end%>
  </div>
</div>

app/views/teachers/groups/new.html.erb
<div class="container pt-5">
  <h1 class="title">New group</h1>

  <%= render "teachers/groups/form", group: @group, method: :post, url: teacher_groups_url(@user, @group) %>

  <div class="is-flex is-justify-content-flex-end">
    <%= link_to(teacher_url(@user), class: "button is-info is-outlined mr-3") do %>
      <i class="fas fa-undo"></i>
      <span class="ml-2">Back to dashboard</span>
    <% end%>
  </div>
<div>

app/views/teachers/groups/show.html.erb
<div class="container pt-5">
  <h2 class="title"><%= @group.name %></h2>
  
  <div class="box">
    <%= render "teachers/groups/group", group:@group %>
  </div>

  <div>
    <span class="sibtitle">
      <strong>Check attendances for</strong>
    </span>

    <%= form_with(method: :get, url: teacher_group_attendances_url(@user, @group)) do |form| %>
      <div class="columns">
        <div class="column">

          <div class="is-flex is-flex-direction-column">
            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label mr-2">From:</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <p class="control">
                    <%= form.date_field :from_date, value: Date.today, required: true, class: "input" %>
                  </p>
                </div>
              </div>
            </div>

            <div class="field is-horizontal">
              <div class="field-label is-normal">
                <label class="label mr-2">To:</label>
              </div>
              <div class="field-body">
                <div class="field">
                  <p class="control">
                    <%= form.date_field :to_date, value: Date.today, required: true, class: "input" %>
                  </p>
                </div>
              </div>
            </div>
            <%= form.submit "View attendance record", class: "button is-primary is-outlined"%>
          </div>

        </div>
        <div class="column">
        </div>
      </div>
    <% end %>
    <br>

    <div class="is-flex is-justify-content-flex-end">
      <%= link_to(teacher_path(@user), class: "button is-info is-outlined mr-5") do %>
        <i class="fas fa-undo"></i>
        <span class="ml-2">Back to dashboard</span>
      <% end %>
      <%= link_to(new_teacher_group_attendance_url(@user, @group), class: "button is-link is-outlined mr-5") do %>
        <i class="far fa-check-square"></i>
        <span class="ml-2">Take attendance</span>
      <% end %>
      <%= link_to(edit_teacher_group_path(@user, @group), class: "button is-primary is-outlined mr-5") do %>
        <i class="fas fa-edit"></i>
        <span class="ml-2">Edit group</span>
      <% end %>
      <%= button_to(teacher_group_url(@user, @group), method: :delete, class: "button is-danger is-outlined", data: { confirm: 'Delete group. Are you sure?' }) do %>
        <i class="fas fa-trash-alt"></i>
        <span class="ml-2">Delete group</span>
      <% end %>
    </div>
  </div>
</div>