config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :teachers, except: [:index] do
    scope module: :teachers do
      resources :debts, except: [:edit] do
        scope module: :debts do
          resources :payments
        end
      end
      resources :students
      resources :montly_payments, only: [:create]
      resources :learning_resources
      resources :reviews, except: [:index]
    end
    resources :groups # TODO: this line seems like is not required
    resources :documents
    resources :groups do
      resources :attendances, except: [:edit, :update, :destroy]
    end
    resources :student_learning_resources, only: [:new, :create, :destroy]
  end

  resources :students, except: [:index, :create, :destroy] do
    scope module: :students do
      resources :learning_resources, only: [:index]
      resources :attendances, only: [:index]
      resources :reviews, only: [:index]
      resources :student_learning_resources, only: [:index]
    end
  end
end
# rubocop:enable Metrics/BlockLength

app/models/learning_resource.rb
class LearningResource < ApplicationRecord
  belongs_to :user
  has_one_attached :resource
  validates :name, presence: true

  has_many :student_learning_resources, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/students/learning_resources_controller.rb
module Students
  class LearningResourcesController < ApplicationController
    before_action :authenticate_user!, :set_user

    def index
      # TODO: fix this 'where' clausule to use @user.belt directly
      @learning_resources = LearningResource.where("belt <= ?", BELTS[@user.belt.to_sym]).paginate(
        page: params[:page], per_page: PER_PAGE
      )
    end

    private

    def set_user
      @user = User.find(params[:student_id])
    end
  end
end

app/controllers/teachers/debts/payments_controller.rb
module Teachers
  module Debts
    class PaymentsController < ApplicationController
      before_action :authenticate_user!, :set_user
      before_action :set_debt, oonly: [:new]

      def new
        @payment = Payment.new
      end

      def create
        payment = PaymentsService.new(payment_params)

        return redirect_to teacher_debts_url(@user), notice: "Payment was successfully applied." if payment.apply

        render :new, status: :unprocessable_entity
      end

      private

      def payment_params
        params.require(:payment).permit(:amount, :debt_id)
      end

      def set_user
        user_id = current_user.id || params[:id]
        @user = User.find(user_id)
      end

      def set_debt
        @debt = Debt.find(params[:debt_id])
      end
    end
  end
end

app/controllers/teachers/debts_controller.rb
module Teachers
  class DebtsController < ApplicationController
    before_action :authenticate_user!, :set_user
    before_action :set_debt, only: [:edit, :update, :destroy, :show]
    before_action :set_teacher_students

    def index
      @debts = @user.my_debts.where(status: DEBTS_STATUS[:pending]).paginate(page: params[:page], per_page: PER_PAGE)
    end

    def show; end

    def new
      @debt = @user.my_debts.new
    end

    def edit; end

    def create
      @debt = @user.my_debts.new(debt_params)

      return redirect_to teacher_debts_url(@user), notice: "Debt was created." if @debt.save

      render :new, status: :unprocessable_entity
    end

    def update
      return redirect_to teacher_debts_url(@user), notice: "Debt was updated." if @debt.update(debt_params)

      render :edit, status: :unprocessable_entity
    end

    def destroy
      @debt.destroy

      redirect_to teacher_debts_url(@user), notice: "Debt was successfully destroyed."
    end

    private

    def set_debt
      @debt = Debt.find(params[:id])
    end

    def debt_params
      params.require(:debt).permit(:amount, :concept, :teacher, :description, :student_id, :status)
    end

    def set_user
      user_id = current_user.id || params[:id]
      @user = User.find(user_id)
    end

    def my_students_ids
      # TODO: nicer approach would be having a instance method responsible of getting that records. (@teacher.students)
      @user.group_members.pluck(:user_id)
    end

    def set_teacher_students
      @my_students = User.where(id: my_students_ids).select(:name, :id)
    end
  end
end

app/controllers/teachers/learning_resources_controller.rb
module Teachers
  class LearningResourcesController < ApplicationController
    before_action :authenticate_user!, :set_user
    before_action :set_teachers_learning_resource, only: [:show, :edit, :update, :destroy]

    def index
      @teacher_learning_resources = @user.learning_resources.paginate(page: params[:page], per_page: PER_PAGE)
    end

    def show; end

    def new
      @teachers_learning_resource = @user.learning_resources.new
    end

    def edit; end

    def create
      @teachers_learning_resource = @user.learning_resources.new(learning_resource_params)

      if @teachers_learning_resource.save
        redirect_to teacher_learning_resources_url(@user), notice: "Learning resource was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @teachers_learning_resource.update(learning_resource_params)
        redirect_to teacher_learning_resources_url(@teachers_learning_resource),
                    notice: "Learning resource was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @teachers_learning_resource.destroy

      redirect_to teacher_learning_resources_url(@user), notice: "Learning resource was successfully destroyed."
    end

    private

    def set_user
      user_id = current_user.id || params[:id]
      @user = User.find(user_id)
    end

    def set_teachers_learning_resource
      @teachers_learning_resource = LearningResource.find(params[:id])
    end

    def learning_resource_params
      params.require(:learning_resource).permit(:name, :description, :belt, :resource)
    end
  end
end

app/controllers/teachers/montly_payments_controller.rb
module Teachers
  class MontlyPaymentsController < ApplicationController
    before_action :authenticate_user!, :set_user

    def create
      my_students.map do |member|
        member.user.debts.create!(
          amount: member.user.student_information.montly_payment,
          concept: "Mensualidad #{Date.today.strftime("%B")}",
          teacher: @user,
          status: "pending"
        )
      end

      redirect_to teacher_debts_url(@user), notice: "Montly payment successfully aplied."
    end

    private

    def set_user
      @user = User.find(params[:teacher_id])
    end

    def my_students
      @user.group_members
    end
  end
end

app/controllers/teachers/reviews_controller.rb
module Teachers
  class ReviewsController < ApplicationController
    before_action :authenticate_user!, :set_user
    before_action :set_teachers_review, only: [:show, :edit, :update, :destroy]
    before_action :set_teacher_students, only: [:new, :edit]

    def show; end

    def new
      @review = Review.new
    end

    def edit; end

    def create
      @review = Review.new(teachers_review_params.merge(teacher: @user))

      return redirect_to teacher_review_url(@user, @review), notice: "Review was successfully created." if @review.save

      render :new, status: :unprocessable_entity
    end

    def update
      if @review.update(teachers_review_params)
        redirect_to teacher_review_url(@user, @review), notice: "Review was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @review.destroy
      redirect_to teacher_student_path(@user, @review.student_id), notice: "Review was successfully destroyed."
    end

    private

    def set_teachers_review
      @review = Review.find(params[:id])
    end

    def set_user
      @user = User.find(params[:teacher_id])
    end

    def teachers_review_params
      params.require(:review).permit(:review, :learning_resource_id, :student_id)
    end

    def my_students_ids
      # TODO: nicer approach would be having a instance method responsible of getting that records. (@teacher.students)
      @user.group_members.pluck(:user_id)
    end

    def set_teacher_students
      @my_students = User.where(id: my_students_ids).select(:name, :id)
    end
  end
end

app/controllers/teachers/students_controller.rb
module Teachers
  class StudentsController < ApplicationController
    before_action :authenticate_user!, :set_user
    before_action :set_student, only: [:show, :edit, :update, :destroy]

    def index
      @students = User.where(id: my_students_ids).paginate(page: params[:page], per_page: PER_PAGE)
    end

    def show
      @attendances = @student.attendances.where(date: from_date..to_date)
      @attendance_stats = @attendances.group(:present).count
    end

    def new
      @student = User.new
    end

    def edit; end

    def create
      @student = User.new(user_params.merge(password: new_user_temp_password, role: "student"))
      if @student.save
        return redirect_to teacher_students_path(@user),
                           notice: "Student created with password #{new_user_temp_password}."
      end

      render :new, status: :unprocessable_entity
    end

    def update
      if @student.update(user_params)
        return redirect_to teacher_students_url(@user), notice: "Student successfully updated."
      end

      render :edit, status: :unprocessable_entity
    end

    def destroy
      @student.destroy
      redirect_to teacher_students_url(@user), notice: "Student successfully destroyed."
    end

    private

    def set_student
      @student = User.find(params[:id])
    end

    def set_user
      @user = User.find(params[:teacher_id])
    end

    def user_params
      params.require(:user).permit(
        :email, :password, :name, :role, :birth_date, :belt,
        group_member_attributes: [:group_id],
        student_information_attributes: [
          :ocupation, :civil_status, :tutor_name, :cellphone, :health_insurance, :montly_payment
        ]
      )
    end

    def new_user_temp_password
      Date.parse(user_params[:birth_date]).strftime('%d%m%y')
    end

    def my_students_ids
      @user.group_members.map(&:user_id)
    end

    def from_date
      params[:from_date] || 1.month.ago
    end

    def to_date
      params[:to_date] || Date.today
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!, :set_user

  def show
    # TODO: This could be a pagination method
    @groups = @user.groups.all
    @total_of_students = @user.group_members.count # TODO: Apply conty catch in to database
    @total_of_learning_resources = @user.learning_resources.count
    # TODO: Add days of the weey to this query
    @in_progress_group = @user.groups
                              .where("from_time <= ?", Time.new)
                              .where("to_time >= ?", Time.new).last
  end

  def new
    @teacher = User.new
  end

  def edit; end

  def create
    @teacher = User.new(user_params.merge(password: new_temp_password, role: "teacher"))

    if @teacher.save
      return redirect_to teacher_path(@user), notice: "Teacher created with password #{new_temp_password}."
    end

    render :new, status: :unprocessable_entity
  end

  def update
    return redirect_to teacher_url(@user), notice: "Profile was successfully updated." if @user.update(user_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @user.destroy
    redirect_to teachers_url, notice: "Teacher was successfully destroyed."
  end

  private

  def set_user
    user_id = params[:id] || current_user.id
    @user = User.find(user_id)
  end

  def user_params
    params.require(:user).permit(:email, :password, :name, :birth_date, :belt)
  end

  def new_temp_password
    Date.parse(user_params[:birth_date]).strftime('%d%m%y')
  end
end

app/views/teachers/learning_resources/_form.html.erb
<%= form_with(model: learning_resource, url: url) do |form| %>
  <% if learning_resource.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(learning_resource.errors.count, "error") %> prohibited this teachers_learning_resource from being saved:</h2>
      <ul>
        <% learning_resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= form.label :name, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control">
          <%= form.text_field :name, value: learning_resource.name, required: true, class:"input" %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= form.label :description, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control">
          <%= form.text_area :description, value: learning_resource.description, required: true, class:"input" %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= form.label :belt, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="select">
          <%= form.select :belt, BELTS_TEXT.invert, value: learning_resource.belt, class: "input"%>
        </div>
      </div>
    </div>
  </div>
  
  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= form.label :resource, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control">
          <%= form.file_field :resource, class:"input" %>
        </p>
      </div>
    </div>
  </div>

  <div class="is-flex is-justify-content-flex-end mt-5">
    <%= form.submit class: "button is-success is-outlined" %>
    <%= link_to(teacher_learning_resources_path(@user), class: "button is-info is-outlined ml-5") do %>
      <i class="fas fa-undo"></i>
      <span class="ml-2">Atras</span>
    <% end %>
  </div>
<% end %>

app/views/teachers/learning_resources/_learning_resource.html.erb
<div id="<%= dom_id learning_resource %>" class="box">
  <div class="columns">
    <div class="column">
      <p>
        <strong>
        Name: <%= learning_resource.name %>
        </strong>
      </p>
      <p>
        <strong>Descripción:</strong>
        <%= learning_resource.description %>
      </p>
      <p>
        <strong>Se requiere cinturón:</strong>
        <%= BELTS_TEXT[BELTS.key(learning_resource.belt)] %>
      </p>

      <% if @user.teacher? %>
        <div class="is-flex is-justify-content-flex-end mt-4 mr-3">
          <%= link_to(edit_teacher_learning_resource_path(@user, learning_resource), class: "button is-info is-outlined ml-5") do %>
            <i class="far fa-edit"></i>
            <span class="ml-2">Editar</span>
          <% end %>

          <%= button_to(teacher_learning_resource_path(@user, learning_resource), method: :delete, class: "button is-danger is-outlined ml-5") do %>
            <i class="far fa-trash-alt"></i>
            <span class="ml-2">Borrar</span>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="column">
      <% if learning_resource.resource.attached? %>
        <p>
          <strong>Recurso:</strong>
          <%= render "file_resource/resource", file_resource: learning_resource %>
        </p>
      <% else %>
          <p>
            <span class="tag is-info is-medium is-light">Este recurso de aprendizaje no tiene un archivo adjunto.</span>
          </p>
      <% end %>
    </div>

  </div>
</div>
<div >




</div>

app/views/teachers/learning_resources/edit.html.erb
<div class="container pt-5">
  <h1 class="title">Editar recurso de aprendizaje</h1>

  <%= render "form", learning_resource: @teachers_learning_resource, url: teacher_learning_resource_path(@user, @teachers_learning_resource) %>
</div>

app/views/teachers/learning_resources/index.html.erb
<div class="container pt-5">
  <h1 class="title">Recursos de aprendizaje</h1>

  <div>
    <% @teacher_learning_resources.each do |learning_resource| %>
      <%= render "teachers/learning_resources/learning_resource", learning_resource: learning_resource%>
    <% end %>
  </div>

  <%= will_paginate @teacher_learning_resources, renderer: RemoteLinkPagination::LinkRenderer, :class=>"" %>

  <div class="is-flex is-justify-content-flex-end">
    <%= link_to(new_teacher_student_learning_resource_url(@user), class: "button is-primary is-outlined ml-5") do %>
      <i class="fas fa-user-plus"></i>
      <span class="ml-2">Asignar al estudiante</span>
    <% end %>
    <%= link_to(new_teacher_learning_resource_path(@user), class: "button is-success is-outlined ml-5") do %>
      <i class="fas fa-plus"></i>
      <span class="ml-2">Crear nueva</span>
    <% end %>
    <%= link_to(teacher_path(@user), class: "button is-info is-outlined ml-5") do %>
      <i class="fas fa-undo"></i>
      <span class="ml-2">Atras</span>
    <% end %>
  </div>
  <br>
</div>

app/views/teachers/learning_resources/new.html.erb
<div class="container pt-5">
  <h1 class="title">Nuevo recurso de aprendizaje</h1>

  <%= render "form", learning_resource: @teachers_learning_resource, url: teacher_learning_resources_path(@user) %>
  <br>
</div>

app/views/teachers/learning_resources/show.html.erb
<%= render @teachers_learning_resource %>

<div>
  <%= link_to "Edit this learning resource", edit_teacher_learning_resource_path(@user, @teachers_learning_resource) %>
  <br>
  <%= link_to "Back to learning resources", teacher_learning_resources_path(@user) %>

  <%= button_to "Destroy this learning resource", teacher_learning_resource_path(@user, @teachers_learning_resource), method: :delete %>
</div>