config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :teachers, except: [:index] do
    scope module: :teachers do
      resources :debts, except: [:edit] do
        scope module: :debts do
          resources :payments
        end
      end
      resources :students
      resources :montly_payments, only: [:create]
      resources :learning_resources
      resources :reviews, except: [:index]
    end
    resources :groups # TODO: this line seems like is not required
    resources :documents
    resources :groups do
      resources :attendances, except: [:edit, :update, :destroy]
    end
    resources :student_learning_resources, only: [:new, :create, :destroy]
  end

  resources :students, except: [:index, :create, :destroy] do
    scope module: :students do
      resources :learning_resources, only: [:index]
      resources :attendances, only: [:index]
      resources :reviews, only: [:index]
      resources :student_learning_resources, only: [:index]
    end
  end
end
# rubocop:enable Metrics/BlockLength

app/controllers/teachers/debts/payments_controller.rb
module Teachers
  module Debts
    class PaymentsController < ApplicationController
      before_action :authenticate_user!, :set_user
      before_action :set_debt, oonly: [:new]

      def new
        @payment = Payment.new
      end

      def create
        payment = PaymentsService.new(payment_params)

        return redirect_to teacher_debts_url(@user), notice: "Payment was successfully applied." if payment.apply

        render :new, status: :unprocessable_entity
      end

      private

      def payment_params
        params.require(:payment).permit(:amount, :debt_id)
      end

      def set_user
        user_id = current_user.id || params[:id]
        @user = User.find(user_id)
      end

      def set_debt
        @debt = Debt.find(params[:debt_id])
      end
    end
  end
end

app/controllers/teachers/debts_controller.rb
module Teachers
  class DebtsController < ApplicationController
    before_action :authenticate_user!, :set_user
    before_action :set_debt, only: [:edit, :update, :destroy, :show]
    before_action :set_teacher_students

    def index
      @debts = @user.my_debts.where(status: DEBTS_STATUS[:pending]).paginate(page: params[:page], per_page: PER_PAGE)
    end

    def show; end

    def new
      @debt = @user.my_debts.new
    end

    def edit; end

    def create
      @debt = @user.my_debts.new(debt_params)

      return redirect_to teacher_debts_url(@user), notice: "Debt was created." if @debt.save

      render :new, status: :unprocessable_entity
    end

    def update
      return redirect_to teacher_debts_url(@user), notice: "Debt was updated." if @debt.update(debt_params)

      render :edit, status: :unprocessable_entity
    end

    def destroy
      @debt.destroy

      redirect_to teacher_debts_url(@user), notice: "Debt was successfully destroyed."
    end

    private

    def set_debt
      @debt = Debt.find(params[:id])
    end

    def debt_params
      params.require(:debt).permit(:amount, :concept, :teacher, :description, :student_id, :status)
    end

    def set_user
      user_id = current_user.id || params[:id]
      @user = User.find(user_id)
    end

    def my_students_ids
      # TODO: nicer approach would be having a instance method responsible of getting that records. (@teacher.students)
      @user.group_members.pluck(:user_id)
    end

    def set_teacher_students
      @my_students = User.where(id: my_students_ids).select(:name, :id)
    end
  end
end

app/controllers/teachers/learning_resources_controller.rb
module Teachers
  class LearningResourcesController < ApplicationController
    before_action :authenticate_user!, :set_user
    before_action :set_teachers_learning_resource, only: [:show, :edit, :update, :destroy]

    def index
      @teacher_learning_resources = @user.learning_resources.paginate(page: params[:page], per_page: PER_PAGE)
    end

    def show; end

    def new
      @teachers_learning_resource = @user.learning_resources.new
    end

    def edit; end

    def create
      @teachers_learning_resource = @user.learning_resources.new(learning_resource_params)

      if @teachers_learning_resource.save
        redirect_to teacher_learning_resources_url(@user), notice: "Learning resource was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @teachers_learning_resource.update(learning_resource_params)
        redirect_to teacher_learning_resources_url(@teachers_learning_resource),
                    notice: "Learning resource was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @teachers_learning_resource.destroy

      redirect_to teacher_learning_resources_url(@user), notice: "Learning resource was successfully destroyed."
    end

    private

    def set_user
      user_id = current_user.id || params[:id]
      @user = User.find(user_id)
    end

    def set_teachers_learning_resource
      @teachers_learning_resource = LearningResource.find(params[:id])
    end

    def learning_resource_params
      params.require(:learning_resource).permit(:name, :description, :belt, :resource)
    end
  end
end

app/controllers/teachers/montly_payments_controller.rb
module Teachers
  class MontlyPaymentsController < ApplicationController
    before_action :authenticate_user!, :set_user

    def create
      my_students.map do |member|
        member.user.debts.create!(
          amount: member.user.student_information.montly_payment,
          concept: "Mensualidad #{Date.today.strftime("%B")}",
          teacher: @user,
          status: "pending"
        )
      end

      redirect_to teacher_debts_url(@user), notice: "Montly payment successfully aplied."
    end

    private

    def set_user
      @user = User.find(params[:teacher_id])
    end

    def my_students
      @user.group_members
    end
  end
end

app/controllers/teachers/reviews_controller.rb
module Teachers
  class ReviewsController < ApplicationController
    before_action :authenticate_user!, :set_user
    before_action :set_teachers_review, only: [:show, :edit, :update, :destroy]
    before_action :set_teacher_students, only: [:new, :edit]

    def show; end

    def new
      @review = Review.new
    end

    def edit; end

    def create
      @review = Review.new(teachers_review_params.merge(teacher: @user))

      return redirect_to teacher_review_url(@user, @review), notice: "Review was successfully created." if @review.save

      render :new, status: :unprocessable_entity
    end

    def update
      if @review.update(teachers_review_params)
        redirect_to teacher_review_url(@user, @review), notice: "Review was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @review.destroy
      redirect_to teacher_student_path(@user, @review.student_id), notice: "Review was successfully destroyed."
    end

    private

    def set_teachers_review
      @review = Review.find(params[:id])
    end

    def set_user
      @user = User.find(params[:teacher_id])
    end

    def teachers_review_params
      params.require(:review).permit(:review, :learning_resource_id, :student_id)
    end

    def my_students_ids
      # TODO: nicer approach would be having a instance method responsible of getting that records. (@teacher.students)
      @user.group_members.pluck(:user_id)
    end

    def set_teacher_students
      @my_students = User.where(id: my_students_ids).select(:name, :id)
    end
  end
end

app/controllers/teachers/students_controller.rb
module Teachers
  class StudentsController < ApplicationController
    before_action :authenticate_user!, :set_user
    before_action :set_student, only: [:show, :edit, :update, :destroy]

    def index
      @students = User.where(id: my_students_ids).paginate(page: params[:page], per_page: PER_PAGE)
    end

    def show
      @attendances = @student.attendances.where(date: from_date..to_date)
      @attendance_stats = @attendances.group(:present).count
    end

    def new
      @student = User.new
    end

    def edit; end

    def create
      @student = User.new(user_params.merge(password: new_user_temp_password, role: "student"))
      if @student.save
        return redirect_to teacher_students_path(@user),
                           notice: "Student created with password #{new_user_temp_password}."
      end

      render :new, status: :unprocessable_entity
    end

    def update
      if @student.update(user_params)
        return redirect_to teacher_students_url(@user), notice: "Student successfully updated."
      end

      render :edit, status: :unprocessable_entity
    end

    def destroy
      @student.destroy
      redirect_to teacher_students_url(@user), notice: "Student successfully destroyed."
    end

    private

    def set_student
      @student = User.find(params[:id])
    end

    def set_user
      @user = User.find(params[:teacher_id])
    end

    def user_params
      params.require(:user).permit(
        :email, :password, :name, :role, :birth_date, :belt,
        group_member_attributes: [:group_id],
        student_information_attributes: [
          :ocupation, :civil_status, :tutor_name, :cellphone, :health_insurance, :montly_payment
        ]
      )
    end

    def new_user_temp_password
      Date.parse(user_params[:birth_date]).strftime('%d%m%y')
    end

    def my_students_ids
      @user.group_members.map(&:user_id)
    end

    def from_date
      params[:from_date] || 1.month.ago
    end

    def to_date
      params[:to_date] || Date.today
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!, :set_user

  def show
    # TODO: This could be a pagination method
    @groups = @user.groups.all
    @total_of_students = @user.group_members.count # TODO: Apply conty catch in to database
    @total_of_learning_resources = @user.learning_resources.count
    # TODO: Add days of the weey to this query
    @in_progress_group = @user.groups
                              .where("from_time <= ?", Time.new)
                              .where("to_time >= ?", Time.new).last
  end

  def new
    @teacher = User.new
  end

  def edit; end

  def create
    @teacher = User.new(user_params.merge(password: new_temp_password, role: "teacher"))

    if @teacher.save
      return redirect_to teacher_path(@user), notice: "Teacher created with password #{new_temp_password}."
    end

    render :new, status: :unprocessable_entity
  end

  def update
    return redirect_to teacher_url(@user), notice: "Profile was successfully updated." if @user.update(user_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @user.destroy
    redirect_to teachers_url, notice: "Teacher was successfully destroyed."
  end

  private

  def set_user
    user_id = params[:id] || current_user.id
    @user = User.find(user_id)
  end

  def user_params
    params.require(:user).permit(:email, :password, :name, :birth_date, :belt)
  end

  def new_temp_password
    Date.parse(user_params[:birth_date]).strftime('%d%m%y')
  end
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, url: url, method: method) do |form| %>

  <% if teacher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(teacher.errors.count, "error") %>  prohibir a este usuario de ser guardado:</h2>
      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= form.label :name, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control">
          <%= form.text_field :name, value: teacher.name, required: true, class: "input" %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= form.label :email, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control">
          <%= form.email_field :email, value: teacher.email, required: true, class: "input" %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= form.label :belt, class: "label" %>
    </div>
    <div class="field-body">
      <div class="select">
        <%= form.select :belt, BELTS_TEXT.invert, value: teacher.belt, required: true, class: "input"%>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <%= form.label :birth_date, class: "label" %>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control">
          <%= form.date_field :birth_date, value: teacher.birth_date, required: true, class:"input" %>
        </p>
      </div>
    </div>
  </div>


  <br>
  <div class="is-flex is-justify-content-flex-end">
    <%= form.submit class: "button is-success is-outlined" %>
    <%= link_to(teacher_path(@user), class: "button is-info is-outlined ml-5") do %>
      <i class="fas fa-undo"></i>
      <span class="ml-2">Volver al panel</span>
    <% end %>
  </div>

<% end %>

app/views/teachers/_groups.html.erb
<div id="teacher_groups">

  <% if @groups %>
    <% @groups.each do |group| %>

      <article class="message is-success is-light">
        <div class="message-body is-light">
          <p>
            <span class="mr-3">
              <i class="fas fa-link"></i>
              <strong>
                <%= link_to group.name, teacher_group_url(@user, group) %>
              </strong>
            </span>
            <%= group.from_time.strftime('%k:%M:%S') %>
            <strong> - </strong>
            <%= group.to_time.strftime('%k:%M:%S') %>
          </p>
        </div>
      </article>
      
    <% end %>
  <% else %>
    <span>Aun no tienes grupos...</span>
  <% end %>

</div>

app/views/teachers/_user.html.erb
<div id="<%= dom_id user %>">

  <p>
    <strong>Nombre:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Belt:</strong>
    <%= BELTS_TEXT[BELTS.key(user.belt)] %>
  </p>

  <p>
    <strong>Cumpleaños:</strong>
    <%= user.birth_date %>
  </p>

  <p>
    <strong>Correo electronico:</strong>
    <%= user.email %>
  </p>
</div>

app/views/teachers/edit.html.erb
<div class="container pt-5">
  <h1 class="title" >Editar mi perfil</h1>
  <%= render 'form', teacher: @user, user: @user, url: teacher_url(@user), method: :patch %>
  <br>
</div>

app/views/teachers/new.html.erb
<div class="container pt-5">
  <h1 class="title" >Registrar nuevo Maestro </h1>
  <%= render 'form', teacher: @teacher, user: @user, url: teachers_url(@user), method: :post %>
  <br>
</div>

app/views/teachers/show.html.erb
<div class="container pt-5">
  <h1 class="title">Panel</h1>

  <% if @in_progress_group.present? %>
    <div class="content">
      <div class="notification is-info">
        <button class="delete"></button>
        <%= link_to "#{@in_progress_group.name} group on clases, take attendance!", new_teacher_group_attendance_url(@user, @in_progress_group) %>
      </div>
    </div>
  <% end %>

  <div class="content">
    <div class="columns ">
    
      <div class="column">
        <div class="box content is-medium">
          <div class="media">
            <div class="media-left">
              <span class="title"><%= @total_of_students %></span>
            </div>
            <div class="media-content">
              <i class="fas fa-users"></i>
              <%= link_to "Students", teacher_students_url(@user), class: "has-text-grey-darker"%>
            </div>
          </div>
        </div>
      </div>

      <div class="column">
        <div class="box content is-medium">
          <div class="media">
            <div class="media-left">
              <span class="title"><%= @user.groups.count %></span>
            </div>
            <div class="media-content">
              <i class="fas fa-user-clock"></i>
              Groups
              <%# <%= link_to "Groups", teacher_groups_url(@user), class: "has-text-grey-darker" %>
            </div>
          </div>
        </div>
      </div>

      <div class="column">
        <div class="box content is-medium">
          <div class="media">
            <div class="media-left">
              <span class="title"><%= @user.learning_resources.all.count %></span>
            </div>
            <div class="media-content">
              <i class="fas fa-chalkboard-teacher"></i>
              <%= link_to "Learning Resources", teacher_learning_resources_url(@user), class: "has-text-grey-darker" %>
            </div>
            <div class="media-content">
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="content">
    <div class="columns is-mobile">
      <div class="column">
        <div class="buttons are-medium">
          <%= link_to "Create group", new_teacher_group_url(@user), class: "button is-info is-outlined" %>
          <%= link_to "Register student", new_teacher_student_url(@user), class: "button is-info is-outlined" %>
          <%= link_to "View students", teacher_students_url(@user), class: "button is-info is-outlined" %>
          <%= link_to "Register teacher", new_teacher_url, user: @user, class: "button is-info is-outlined" %>
          <%= link_to "My learning resources", teacher_learning_resources_url(@user), class: "button is-info is-outlined" %>
          <%= link_to "Edit my profile", edit_teacher_url(@user), class: "button is-info is-outlined" %>
          <%= link_to "Assign learning resource", new_teacher_student_learning_resource_url(@user), class: "button is-info is-outlined" %>
          <%= link_to "Create learning resource", new_teacher_learning_resource_url(@user), class: "button is-info is-outlined" %>
          <%= link_to "Review student", new_teacher_review_url(@user), class: "button is-info is-outlined" %>
          <%# duedas %>
          <%= link_to "View debts", teacher_debts_url(@user), class: "button is-info is-outlined" %>
        </div>
      </div>
    </div>
  </div>

  <h2 class="title">Mis grupos</h2>
  <%= render 'groups', groups: @groups %>

  <br />
</div>